package com.commercecore.api.common.entity;

import jakarta.persistence.Column;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.Version;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.UUID;

/**
 * Base entity providing common fields for all domain entities.
 *
 * <p>Every entity in CommerceCore extends this class to inherit:
 * <ul>
 *     <li><b>id</b> — UUID primary key (generated by Hibernate, stored as PostgreSQL UUID)</li>
 *     <li><b>createdAt / updatedAt</b> — Audit timestamps in UTC</li>
 *     <li><b>createdBy / updatedBy</b> — Audit user tracking (populated via {@link org.springframework.data.domain.AuditorAware})</li>
 *     <li><b>version</b> — Optimistic locking counter (prevents lost updates on concurrent edits)</li>
 *     <li><b>deleted / deletedAt</b> — Soft delete support</li>
 * </ul>
 *
 * <p><b>Design decisions:</b>
 * <ul>
 *     <li>UUID over auto-increment: no enumeration attacks, globally unique, merge-safe across environments</li>
 *     <li>Instant over LocalDateTime: always UTC, no timezone ambiguity</li>
 *     <li>@Version for optimistic locking: throws {@link jakarta.persistence.OptimisticLockException}
 *         when two transactions try to update the same row concurrently</li>
 *     <li>Soft delete at entity level: business data is never truly deleted, enables audit compliance and recovery</li>
 * </ul>
 */
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
public abstract class BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false, columnDefinition = "UUID")
    private UUID id;

    @CreatedDate
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(nullable = false)
    private Instant updatedAt;

    @CreatedBy
    @Column(updatable = false)
    private String createdBy;

    @LastModifiedBy
    private String updatedBy;

    @Version
    private Long version;

    @Column(nullable = false)
    private boolean deleted = false;

    private Instant deletedAt;

}
